version: '3.8'

services:
  db:
    image: mongo:4.1.13
    container_name: db
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - net_A

  server:
    image: aoporski/mongo-api:latest
    container_name: server
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - net_A

volumes:
  mongo_data:

networks:
  net_A:
    driver: bridge

# version: '3.8'

# services:
#   db:
#     image: mongo:4.1.13
#     container_name: db
#     ports:
#       - "27019:27017"
#     volumes:
#       - mongo_data:/data/db
#     networks:
#       - net_A

# volumes:
#   mongo_data:

# networks:
#   net_A:
#     driver: bridge